"""
Image-to-3D service using TripoSR.

TripoSR repo: https://github.com/VAST-AI-Research/TripoSR
Model weights: stabilityai/TripoSR on HuggingFace

Integration notes:
- TripoSR must be cloned/installed separately (see README)
- The model expects a single-object image with clean background
- Output is a trimesh object that we export to OBJ/GLB
"""

import shutil
from pathlib import Path

import torch
import numpy as np
from PIL import Image

from app.core.config import get_settings
from app.core.logging import get_logger
from app.services.base import ImageTo3DService

logger = get_logger(__name__)
settings = get_settings()


class TripoSRImageTo3DService(ImageTo3DService):
    """
    TripoSR-based image to 3D model conversion.

    Requires: pip install tsr (or TripoSR cloned locally)

    The actual TripoSR API may vary depending on version.
    This implementation targets the HuggingFace-compatible API.
    """

    def __init__(self) -> None:
        self._model = None

    def load_model(self) -> None:
        if self._model is not None:
            logger.info("TripoSR model already loaded")
            return

        try:
            from tsr.system import TSR

            logger.info(f"Loading TripoSR model: {settings.TRIPOSR_MODEL}")

            self._model = TSR.from_pretrained(
                settings.TRIPOSR_MODEL,
                config_name="config.yaml",
                weight_name="model.ckpt",
            )
            self._model.renderer.set_chunk_size(settings.TRIPOSR_CHUNK_SIZE)
            self._model.to(settings.TRIPOSR_DEVICE)

            logger.info("TripoSR model loaded successfully")

        except ImportError:
            logger.error(
                "TripoSR (tsr) not installed. "
                "Install it from: https://github.com/VAST-AI-Research/TripoSR\n"
                "  git clone https://github.com/VAST-AI-Research/TripoSR.git\n"
                "  cd TripoSR && pip install -e ."
            )
            raise

    def _preprocess_image(self, image: Image.Image) -> Image.Image:
        """Preprocess image for TripoSR: remove background, center object."""
        try:
            import rembg
            logger.info("Removing background with rembg")
            image = rembg.remove(image)
        except ImportError:
            logger.warning("rembg not installed, using image as-is")

        # Ensure RGBA
        if image.mode != "RGBA":
            image = image.convert("RGBA")

        return image

    def generate(self, image: Image.Image, output_dir: Path) -> Path:
        if self._model is None:
            self.load_model()

        output_dir.mkdir(parents=True, exist_ok=True)

        # Preprocess
        processed = self._preprocess_image(image)

        logger.info("Running TripoSR inference...")

        with torch.no_grad():
            scene_codes = self._model([processed], device=settings.TRIPOSR_DEVICE)

        logger.info("Extracting mesh...")

        meshes = self._model.extract_mesh(
            scene_codes,
            resolution=settings.TRIPOSR_MC_RESOLUTION,
        )

        mesh = meshes[0]
        output_path = output_dir / "mesh.obj"
        mesh.export(str(output_path))

        logger.info(f"Mesh exported to {output_path}")
        return output_path

    def unload_model(self) -> None:
        if self._model is not None:
            del self._model
            self._model = None
            torch.cuda.empty_cache()
            logger.info("TripoSR model unloaded")


class MockImageTo3DService(ImageTo3DService):
    """
    Mock service that generates a simple cube OBJ for testing.
    """

    def load_model(self) -> None:
        logger.info("Mock image-to-3D service loaded")

    def generate(self, image: Image.Image, output_dir: Path) -> Path:
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / "mesh.obj"

        logger.info(f"Mock generating 3D model at {output_path}")

        # Generate a simple cube OBJ
        obj_content = """# Mock 3D model - cube
# Generated by ModelGenerator mock service
mtllib mesh.mtl

v -0.5 -0.5  0.5
v  0.5 -0.5  0.5
v  0.5  0.5  0.5
v -0.5  0.5  0.5
v -0.5 -0.5 -0.5
v  0.5 -0.5 -0.5
v  0.5  0.5 -0.5
v -0.5  0.5 -0.5

vt 0.0 0.0
vt 1.0 0.0
vt 1.0 1.0
vt 0.0 1.0

vn 0.0 0.0 1.0
vn 0.0 0.0 -1.0
vn 1.0 0.0 0.0
vn -1.0 0.0 0.0
vn 0.0 1.0 0.0
vn 0.0 -1.0 0.0

usemtl material0

f 1/1/1 2/2/1 3/3/1 4/4/1
f 5/1/2 8/2/2 7/3/2 6/4/2
f 2/1/3 6/2/3 7/3/3 3/4/3
f 1/1/4 4/2/4 8/3/4 5/4/4
f 4/1/5 3/2/5 7/3/5 8/4/5
f 1/1/6 5/2/6 6/3/6 2/4/6
"""
        output_path.write_text(obj_content)

        # Generate basic MTL file
        mtl_content = """# Mock material
newmtl material0
Ka 0.2 0.2 0.2
Kd 0.6 0.6 0.8
Ks 0.3 0.3 0.3
Ns 50.0
d 1.0
illum 2
"""
        mtl_path = output_dir / "mesh.mtl"
        mtl_path.write_text(mtl_content)

        return output_path

    def unload_model(self) -> None:
        logger.info("Mock image-to-3D service unloaded")
